### ISSUE TITLE
How generalized should SuggestionRow be?

### ISSUE THREAD

**Issue by lognaturel** [EurekaCommunity/SuggestionRow#1]
Currently, it can only be used to provide `String` suggestions. Should it be generalized so that, for example, the `GooglePlaces` example can be created from it? I'm not sure how possible or desirable that is.

@mats-claassen Interested in hearing what you think.

**Comment by mats-claassen** [comment]
I think it is. Not just for Google Places but for any struct or class we want to choose from.

I would create a protocol and make the value type of SuggestionRow (which currently is String) be a generic type that conforms to that protocol.
And then that protocol must have a method so that you can get a String to display for every element. 

I believe it is better to use a custom protocol for this instead of using `description` or something similar because variables/functions like 'description' might already be defined and we might want to display something custom in the cell.

_FieldCell does only require its type to be `InputTypeInitiable` so that the new protocol should also require that.

Do you see any special problem with this approach?

**Comment by lognaturel** [comment]
Ok, will try to see what I can do. Not sure when I'll get to it but hopefully soon.

I guess the one concern I have is that the abstraction makes things harder to follow and from reading some of the questions in the Eureka issue tracker, it sounds like it keeps some people from attempting to create their own custom rows. I think having some examples that are more focused and not maximally abstracted might help make the idea of custom rows less intimidating. But it doesn't have to be this one!
